language: go
go:
- "1.11"
sudo: false
before_script:
#  - go vet ./... for aborting if build fails later
- git clone https://github.com/jwilder/docker-gen.git	/home/travis/gopath/src/github.com/jwilder/docker-gen

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - make get-deps
script:
- make all check-gofmt test
